services:
  gateway:
    container_name: lingopi-gateway
    image: "lingopi-gateway"
    restart: always
    networks:
      - lingopi-backend
    ports:
      - 44000:5000
    build:
      context: ./src
      dockerfile: Lingopi.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=$ENV
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  identity:
    container_name: lingopi-identity
    image: "lingopi-identity"
    restart: always
    networks:
      - lingopi-backend
    build:
      context: ./src
      dockerfile: Lingopi.Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=$ENV
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  blog:
    container_name: lingopi-blog
    image: "lingopi-blog"
    restart: always
    networks:
      - lingopi-backend
    build:
      context: ./src
      dockerfile: Lingopi.Blog/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=$ENV
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  redis:
    container_name: lingopi-redis
    image: redis:7-alpine
    restart: always
    networks:
      - lingopi-backend
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:
    driver: local

networks:
  lingopi-backend:
    name: lingopi-backend
    driver: bridge
