### Capture a new Lingo - Minimal example
POST http://localhost:5000/api/lingos/
Content-Type: application/json

{
  "userId": "user-019c006a67fa7ae299ef23af44cb3454",
  "originalText": "serendipity",
  "sourceLocaleCode": "en-UK"
}

### Capture a new Lingo - Without source language
POST http://localhost:5000/api/lingos/
Content-Type: application/json

{
  "userId": "user-019c006a67fa7ae299ef23af44cb3454",
  "originalText": "break the ice"
}
