<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Lingopi.Core</PackageId>
    <Version>0.1.0</Version>
    <Authors>Hadi Samadzad</Authors>
    <Description>This class library consists classes that are common among the microservices</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Damas.Operations" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="Hashids.net" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>
</Project>
