name: 🛡️ Security Checks

on:
  workflow_call:
  workflow_dispatch:
  #push:
  #  branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  pull-requests: read
  contents: read

jobs:
  security-checks:
    name: 🛡️ Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: 🔍 Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          file-pattern: '**/*.csproj'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'