name: 🧩 Run Unit Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run-tests:
    name: 🧩 Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v7

      - name: 🔧 Install .NET SDK
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - name: 🚀 Run unit tests
        run: |
          dotnet restore
          dotnet build
          dotnet test --solution Lingopi.slnx --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml --report-xunit-trx --report-xunit-trx-filename test_results.trx

      - name: 📊 Generate Coverage Report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.5.11
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: 'coverage-report'
          reporttypes: 'HtmlInline;Cobertura;TextSummary'

      - name: 📤 Upload Coverage Report
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: coverage-report

      - name: 📊 Upload Test Results
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: '**/test_results.trx'
